name: Install Go and Dependencies
description: Install Go and Go Dependencies
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Download Go dependencies
      shell: bash
      run: |
        go mod download
        pushd tools
        go mod download
        popd
