version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - makezero
    - nakedret
    - nilnil
    - paralleltest
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-len: 5
      min-occurrences: 5
    gocyclo:
      min-complexity: 20
    godot:
      capital: true
      period: true
    lll:
      line-length: 120
      tab-width: 2
    nakedret:
      max-func-lines: 20
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          arguments:
            - 8
        - name: bare-return
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: file-header
          arguments:
            - The Things Network Foundation, The Things Industries B.V.
        - name: flag-parameter
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          arguments:
            - 3
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: nested-structs
          disabled: true
        - name: unhandled-error
          disabled: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - paralleltest
        text: does not use range value in test Run
    paths:
      - node_modules
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - node_modules
      - third_party$
      - builtin$
      - examples$
