// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/contact_info.proto

package ttnpb

import (
	context "context"
	fmt "fmt"
	_ "github.com/TheThingsIndustries/protoc-gen-go-json/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	strconv "strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ContactType int32

const (
	CONTACT_TYPE_OTHER     ContactType = 0
	CONTACT_TYPE_ABUSE     ContactType = 1
	CONTACT_TYPE_BILLING   ContactType = 2
	CONTACT_TYPE_TECHNICAL ContactType = 3
)

var ContactType_name = map[int32]string{
	0: "CONTACT_TYPE_OTHER",
	1: "CONTACT_TYPE_ABUSE",
	2: "CONTACT_TYPE_BILLING",
	3: "CONTACT_TYPE_TECHNICAL",
}

var ContactType_value = map[string]int32{
	"CONTACT_TYPE_OTHER":     0,
	"CONTACT_TYPE_ABUSE":     1,
	"CONTACT_TYPE_BILLING":   2,
	"CONTACT_TYPE_TECHNICAL": 3,
}

func (ContactType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3baa36b7c4d52524, []int{0}
}

type ContactMethod int32

const (
	CONTACT_METHOD_OTHER ContactMethod = 0
	CONTACT_METHOD_EMAIL ContactMethod = 1
	CONTACT_METHOD_PHONE ContactMethod = 2
)

var ContactMethod_name = map[int32]string{
	0: "CONTACT_METHOD_OTHER",
	1: "CONTACT_METHOD_EMAIL",
	2: "CONTACT_METHOD_PHONE",
}

var ContactMethod_value = map[string]int32{
	"CONTACT_METHOD_OTHER": 0,
	"CONTACT_METHOD_EMAIL": 1,
	"CONTACT_METHOD_PHONE": 2,
}

func (ContactMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3baa36b7c4d52524, []int{1}
}

type ContactInfo struct {
	ContactType          ContactType      `protobuf:"varint,1,opt,name=contact_type,json=contactType,proto3,enum=ttn.lorawan.v3.ContactType" json:"contact_type,omitempty"`
	ContactMethod        ContactMethod    `protobuf:"varint,2,opt,name=contact_method,json=contactMethod,proto3,enum=ttn.lorawan.v3.ContactMethod" json:"contact_method,omitempty"`
	Value                string           `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Public               bool             `protobuf:"varint,4,opt,name=public,proto3" json:"public,omitempty"`
	ValidatedAt          *types.Timestamp `protobuf:"bytes,5,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ContactInfo) Reset()         { *m = ContactInfo{} }
func (m *ContactInfo) String() string { return proto.CompactTextString(m) }
func (*ContactInfo) ProtoMessage()    {}
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3baa36b7c4d52524, []int{0}
}
func (m *ContactInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactInfo.Unmarshal(m, b)
}
func (m *ContactInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactInfo.Marshal(b, m, deterministic)
}
func (m *ContactInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactInfo.Merge(m, src)
}
func (m *ContactInfo) XXX_Size() int {
	return xxx_messageInfo_ContactInfo.Size(m)
}
func (m *ContactInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContactInfo proto.InternalMessageInfo

func (m *ContactInfo) GetContactType() ContactType {
	if m != nil {
		return m.ContactType
	}
	return CONTACT_TYPE_OTHER
}

func (m *ContactInfo) GetContactMethod() ContactMethod {
	if m != nil {
		return m.ContactMethod
	}
	return CONTACT_METHOD_OTHER
}

func (m *ContactInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ContactInfo) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *ContactInfo) GetValidatedAt() *types.Timestamp {
	if m != nil {
		return m.ValidatedAt
	}
	return nil
}

type ContactInfoValidation struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string             `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Entity               *EntityIdentifiers `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	ContactInfo          []*ContactInfo     `protobuf:"bytes,4,rep,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	CreatedAt            *types.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt            *types.Timestamp   `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ContactInfoValidation) Reset()         { *m = ContactInfoValidation{} }
func (m *ContactInfoValidation) String() string { return proto.CompactTextString(m) }
func (*ContactInfoValidation) ProtoMessage()    {}
func (*ContactInfoValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3baa36b7c4d52524, []int{1}
}
func (m *ContactInfoValidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactInfoValidation.Unmarshal(m, b)
}
func (m *ContactInfoValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactInfoValidation.Marshal(b, m, deterministic)
}
func (m *ContactInfoValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactInfoValidation.Merge(m, src)
}
func (m *ContactInfoValidation) XXX_Size() int {
	return xxx_messageInfo_ContactInfoValidation.Size(m)
}
func (m *ContactInfoValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactInfoValidation.DiscardUnknown(m)
}

var xxx_messageInfo_ContactInfoValidation proto.InternalMessageInfo

func (m *ContactInfoValidation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContactInfoValidation) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ContactInfoValidation) GetEntity() *EntityIdentifiers {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *ContactInfoValidation) GetContactInfo() []*ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *ContactInfoValidation) GetCreatedAt() *types.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ContactInfoValidation) GetExpiresAt() *types.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("ttn.lorawan.v3.ContactType", ContactType_name, ContactType_value)
	golang_proto.RegisterEnum("ttn.lorawan.v3.ContactType", ContactType_name, ContactType_value)
	proto.RegisterEnum("ttn.lorawan.v3.ContactMethod", ContactMethod_name, ContactMethod_value)
	golang_proto.RegisterEnum("ttn.lorawan.v3.ContactMethod", ContactMethod_name, ContactMethod_value)
	proto.RegisterType((*ContactInfo)(nil), "ttn.lorawan.v3.ContactInfo")
	golang_proto.RegisterType((*ContactInfo)(nil), "ttn.lorawan.v3.ContactInfo")
	proto.RegisterType((*ContactInfoValidation)(nil), "ttn.lorawan.v3.ContactInfoValidation")
	golang_proto.RegisterType((*ContactInfoValidation)(nil), "ttn.lorawan.v3.ContactInfoValidation")
}

func init() {
	proto.RegisterFile("lorawan-stack/api/contact_info.proto", fileDescriptor_3baa36b7c4d52524)
}
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/contact_info.proto", fileDescriptor_3baa36b7c4d52524)
}

var fileDescriptor_3baa36b7c4d52524 = []byte{
	// 765 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xbf, 0x8f, 0xe2, 0x46,
	0x14, 0xde, 0x31, 0x0b, 0x5a, 0x86, 0x3d, 0xe4, 0x4c, 0x12, 0xe4, 0xf5, 0xe5, 0x38, 0xc2, 0x25,
	0x12, 0x42, 0xc2, 0x96, 0xd8, 0xea, 0x22, 0x5d, 0x14, 0x43, 0xac, 0x80, 0xc4, 0xc2, 0xc9, 0x71,
	0x22, 0x25, 0x0d, 0x32, 0x66, 0x30, 0x13, 0x60, 0xc6, 0xb1, 0x07, 0xee, 0xdc, 0x45, 0x5b, 0x45,
	0x91, 0x52, 0xa5, 0x4f, 0x93, 0xee, 0xfe, 0x8a, 0x14, 0xf9, 0x0f, 0xf2, 0x1f, 0x5c, 0x52, 0x44,
	0x5b, 0xa5, 0xde, 0xea, 0xc4, 0x60, 0xc0, 0x5e, 0xb4, 0x3f, 0x3a, 0xcf, 0xfb, 0xbe, 0xf7, 0xde,
	0xcc, 0xf7, 0x3d, 0x3f, 0xf8, 0xc9, 0x9c, 0x05, 0xce, 0x2b, 0x87, 0x36, 0x42, 0xee, 0xb8, 0x33,
	0xdd, 0xf1, 0x89, 0xee, 0x32, 0xca, 0x1d, 0x97, 0x0f, 0x09, 0x9d, 0x30, 0xcd, 0x0f, 0x18, 0x67,
	0xa8, 0xc8, 0x39, 0xd5, 0x62, 0xa6, 0xb6, 0x3a, 0x57, 0x0d, 0x8f, 0xf0, 0xe9, 0x72, 0xa4, 0xb9,
	0x6c, 0xa1, 0x63, 0xba, 0x62, 0x91, 0x1f, 0xb0, 0xd7, 0x91, 0x2e, 0xc8, 0x6e, 0xc3, 0xc3, 0xb4,
	0xb1, 0x72, 0xe6, 0x64, 0xec, 0x70, 0xac, 0x1f, 0x7c, 0x6c, 0x4a, 0xaa, 0x8d, 0x44, 0x09, 0x8f,
	0x79, 0x6c, 0x93, 0x3c, 0x5a, 0x4e, 0xc4, 0x49, 0x1c, 0xc4, 0x57, 0x4c, 0x6f, 0x27, 0xe8, 0xf6,
	0x14, 0xdb, 0x53, 0x42, 0xbd, 0xb0, 0x4b, 0xc7, 0xcb, 0x90, 0x07, 0x04, 0x87, 0xc9, 0xd6, 0x1e,
	0x6b, 0xfc, 0x10, 0x32, 0xaa, 0x3b, 0x94, 0x32, 0xee, 0x70, 0xc2, 0x68, 0x18, 0x17, 0xf9, 0xc8,
	0x63, 0xcc, 0x9b, 0x63, 0xf1, 0xca, 0x43, 0xf4, 0x71, 0x8c, 0xee, 0x2e, 0x82, 0x17, 0x3e, 0x8f,
	0x62, 0xf0, 0xe9, 0x4d, 0x90, 0x93, 0x05, 0x0e, 0xb9, 0xb3, 0xf0, 0x63, 0xc2, 0xb3, 0x43, 0x21,
	0xc9, 0x18, 0x53, 0x4e, 0x26, 0x04, 0x07, 0x71, 0x8b, 0xea, 0xef, 0x12, 0x2c, 0xb4, 0x37, 0xf2,
	0x76, 0xe9, 0x84, 0xa1, 0x0e, 0x3c, 0xdd, 0xaa, 0xcd, 0x23, 0x1f, 0x2b, 0xa0, 0x02, 0x6a, 0xc5,
	0xe6, 0x63, 0x2d, 0x2d, 0xb7, 0x16, 0xa7, 0xd8, 0x91, 0x8f, 0x5b, 0x27, 0xd7, 0xad, 0xec, 0x25,
	0x90, 0x64, 0x60, 0x15, 0xdc, 0x7d, 0x18, 0xf5, 0x61, 0x71, 0x5b, 0x69, 0x81, 0xf9, 0x94, 0x8d,
	0x15, 0x49, 0xd4, 0x7a, 0x72, 0x4b, 0xad, 0x0b, 0x41, 0x4a, 0x54, 0x7b, 0xe4, 0x26, 0x01, 0x54,
	0x86, 0xd9, 0x95, 0x33, 0x5f, 0x62, 0x25, 0x53, 0x01, 0xb5, 0xbc, 0xe0, 0x05, 0x19, 0xe5, 0x27,
	0xc9, 0xda, 0x84, 0x51, 0x09, 0xe6, 0xfc, 0xe5, 0x68, 0x4e, 0x5c, 0xe5, 0xb8, 0x02, 0x6a, 0x27,
	0x56, 0x7c, 0x42, 0x2f, 0xe0, 0xe9, 0xd6, 0xe8, 0xf1, 0xd0, 0xe1, 0x4a, 0xb6, 0x02, 0x6a, 0x85,
	0xa6, 0xaa, 0x6d, 0xe4, 0xd3, 0xb6, 0xf2, 0x69, 0xf6, 0x56, 0x3e, 0xab, 0xb0, 0xe3, 0x1b, 0xbc,
	0xfa, 0x97, 0x04, 0x3f, 0x4c, 0x08, 0xf4, 0xed, 0x06, 0x22, 0x8c, 0xa2, 0x33, 0x28, 0x91, 0xb1,
	0x10, 0x28, 0xdf, 0xca, 0x5f, 0xb7, 0x72, 0xc1, 0xb1, 0x0c, 0x94, 0x2f, 0x2c, 0x89, 0x8c, 0xd1,
	0x53, 0x98, 0xe5, 0x6c, 0x86, 0xa9, 0x78, 0x72, 0x0a, 0xdd, 0xc4, 0xd1, 0x73, 0x98, 0x5b, 0x3b,
	0xc1, 0x23, 0xf1, 0x9a, 0x42, 0xf3, 0xe3, 0x9b, 0xa2, 0x98, 0x02, 0xed, 0xee, 0xfd, 0xb2, 0xe2,
	0x04, 0xf4, 0xf9, 0xde, 0xa1, 0xf5, 0xff, 0xa0, 0x1c, 0x57, 0x32, 0xb5, 0xc2, 0xad, 0x0e, 0xad,
	0xef, 0xbc, 0xf3, 0x45, 0x38, 0xfc, 0x1c, 0x42, 0x37, 0xc0, 0x0f, 0x57, 0x23, 0x1f, 0xb3, 0x0d,
	0xbe, 0x4e, 0xc5, 0xaf, 0x7d, 0x12, 0xe0, 0x70, 0x9d, 0x9a, 0xbb, 0x3f, 0x35, 0x66, 0x1b, 0xbc,
	0xfe, 0x2b, 0xd8, 0xcd, 0x99, 0x98, 0x8e, 0x12, 0x44, 0xed, 0x41, 0xdf, 0x36, 0xda, 0xf6, 0xd0,
	0xfe, 0xee, 0xa5, 0x39, 0x1c, 0xd8, 0x1d, 0xd3, 0x92, 0x8f, 0x0e, 0xe2, 0x46, 0xeb, 0x9b, 0xaf,
	0x4d, 0x19, 0x20, 0x05, 0x7e, 0x90, 0x8a, 0xb7, 0xba, 0xbd, 0x5e, 0xb7, 0xff, 0x95, 0x2c, 0x21,
	0x15, 0x96, 0x52, 0x88, 0x6d, 0xb6, 0x3b, 0xfd, 0x6e, 0xdb, 0xe8, 0xc9, 0x19, 0x55, 0xb9, 0x7a,
	0x73, 0x26, 0x2b, 0xa0, 0x7e, 0x9a, 0x64, 0xfc, 0xfc, 0x47, 0xf9, 0xa8, 0x1e, 0xc1, 0x47, 0xa9,
	0xb9, 0x4b, 0x36, 0xb8, 0x30, 0xed, 0xce, 0xe0, 0xcb, 0xdd, 0x95, 0x0e, 0x11, 0xf3, 0xc2, 0xe8,
	0xf6, 0xd2, 0x97, 0x8a, 0x91, 0x97, 0x9d, 0x41, 0xdf, 0x94, 0x25, 0x55, 0xbd, 0x7a, 0x73, 0x86,
	0x14, 0x50, 0x2f, 0xa6, 0xf1, 0x75, 0xeb, 0xe6, 0x2f, 0x12, 0x7c, 0x3f, 0xe9, 0x0e, 0xf6, 0x48,
	0xc8, 0x83, 0x08, 0x5d, 0x02, 0xf8, 0x9e, 0x85, 0x7f, 0x5c, 0xe2, 0x90, 0x27, 0xa6, 0xec, 0xfe,
	0xc9, 0x50, 0x3f, 0xbd, 0xc3, 0xfb, 0x7d, 0xa5, 0xea, 0xb3, 0xcb, 0xbf, 0xff, 0xfd, 0x4d, 0x7a,
	0x52, 0x55, 0x52, 0xfb, 0x74, 0xbb, 0x05, 0x09, 0xa3, 0x9f, 0x81, 0x3a, 0xa2, 0xf0, 0x24, 0x4e,
	0xc1, 0xe8, 0x61, 0x75, 0xd5, 0xd2, 0xc1, 0x04, 0x98, 0xeb, 0x35, 0xb5, 0xed, 0xd7, 0xbc, 0xab,
	0x5f, 0xeb, 0xc5, 0x7f, 0x6f, 0xcb, 0x47, 0xff, 0xbf, 0x2d, 0x83, 0x3f, 0xff, 0x29, 0x83, 0xef,
	0x75, 0x8f, 0x69, 0x7c, 0x8a, 0xb9, 0xd8, 0xa5, 0x1a, 0xc5, 0xfc, 0x15, 0x0b, 0x66, 0x7a, 0x7a,
	0x8f, 0xad, 0xce, 0x75, 0x7f, 0xe6, 0xe9, 0x9c, 0x53, 0x7f, 0x34, 0xca, 0x89, 0x9e, 0xe7, 0xef,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xef, 0x67, 0xc1, 0xea, 0x35, 0x06, 0x00, 0x00,
}

func (x ContactType) String() string {
	s, ok := ContactType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x ContactMethod) String() string {
	s, ok := ContactMethod_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactInfoRegistryClient is the client API for ContactInfoRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactInfoRegistryClient interface {
	// Request validation for the non-validated contact info for the given entity.
	RequestValidation(ctx context.Context, in *EntityIdentifiers, opts ...grpc.CallOption) (*ContactInfoValidation, error)
	// Validate confirms a contact info validation.
	Validate(ctx context.Context, in *ContactInfoValidation, opts ...grpc.CallOption) (*types.Empty, error)
}

type contactInfoRegistryClient struct {
	cc *grpc.ClientConn
}

func NewContactInfoRegistryClient(cc *grpc.ClientConn) ContactInfoRegistryClient {
	return &contactInfoRegistryClient{cc}
}

func (c *contactInfoRegistryClient) RequestValidation(ctx context.Context, in *EntityIdentifiers, opts ...grpc.CallOption) (*ContactInfoValidation, error) {
	out := new(ContactInfoValidation)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ContactInfoRegistry/RequestValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactInfoRegistryClient) Validate(ctx context.Context, in *ContactInfoValidation, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.ContactInfoRegistry/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactInfoRegistryServer is the server API for ContactInfoRegistry service.
type ContactInfoRegistryServer interface {
	// Request validation for the non-validated contact info for the given entity.
	RequestValidation(context.Context, *EntityIdentifiers) (*ContactInfoValidation, error)
	// Validate confirms a contact info validation.
	Validate(context.Context, *ContactInfoValidation) (*types.Empty, error)
}

// UnimplementedContactInfoRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedContactInfoRegistryServer struct {
}

func (*UnimplementedContactInfoRegistryServer) RequestValidation(ctx context.Context, req *EntityIdentifiers) (*ContactInfoValidation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestValidation not implemented")
}
func (*UnimplementedContactInfoRegistryServer) Validate(ctx context.Context, req *ContactInfoValidation) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterContactInfoRegistryServer(s *grpc.Server, srv ContactInfoRegistryServer) {
	s.RegisterService(&_ContactInfoRegistry_serviceDesc, srv)
}

func _ContactInfoRegistry_RequestValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdentifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactInfoRegistryServer).RequestValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ContactInfoRegistry/RequestValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactInfoRegistryServer).RequestValidation(ctx, req.(*EntityIdentifiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactInfoRegistry_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactInfoValidation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactInfoRegistryServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.ContactInfoRegistry/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactInfoRegistryServer).Validate(ctx, req.(*ContactInfoValidation))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactInfoRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ttn.lorawan.v3.ContactInfoRegistry",
	HandlerType: (*ContactInfoRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestValidation",
			Handler:    _ContactInfoRegistry_RequestValidation_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _ContactInfoRegistry_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorawan-stack/api/contact_info.proto",
}
