// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/identifiers.proto

package ttnpb

import (
	fmt "fmt"
	_ "github.com/TheThingsIndustries/protoc-gen-go-flags/annotations"
	_ "github.com/TheThingsIndustries/protoc-gen-go-json/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationIdentifiers struct {
	ApplicationId        string   `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationIdentifiers) Reset()         { *m = ApplicationIdentifiers{} }
func (m *ApplicationIdentifiers) String() string { return proto.CompactTextString(m) }
func (*ApplicationIdentifiers) ProtoMessage()    {}
func (*ApplicationIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{0}
}
func (m *ApplicationIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationIdentifiers.Unmarshal(m, b)
}
func (m *ApplicationIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationIdentifiers.Marshal(b, m, deterministic)
}
func (m *ApplicationIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationIdentifiers.Merge(m, src)
}
func (m *ApplicationIdentifiers) XXX_Size() int {
	return xxx_messageInfo_ApplicationIdentifiers.Size(m)
}
func (m *ApplicationIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationIdentifiers proto.InternalMessageInfo

func (m *ApplicationIdentifiers) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

type ClientIdentifiers struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientIdentifiers) Reset()         { *m = ClientIdentifiers{} }
func (m *ClientIdentifiers) String() string { return proto.CompactTextString(m) }
func (*ClientIdentifiers) ProtoMessage()    {}
func (*ClientIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{1}
}
func (m *ClientIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIdentifiers.Unmarshal(m, b)
}
func (m *ClientIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIdentifiers.Marshal(b, m, deterministic)
}
func (m *ClientIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIdentifiers.Merge(m, src)
}
func (m *ClientIdentifiers) XXX_Size() int {
	return xxx_messageInfo_ClientIdentifiers.Size(m)
}
func (m *ClientIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIdentifiers proto.InternalMessageInfo

func (m *ClientIdentifiers) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type EndDeviceIdentifiers struct {
	DeviceId       string                  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ApplicationIds *ApplicationIdentifiers `protobuf:"bytes,2,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	// The LoRaWAN DevEUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// The LoRaWAN JoinEUI (AppEUI until LoRaWAN 1.0.3 end devices).
	JoinEui []byte `protobuf:"bytes,5,opt,name=join_eui,json=joinEui,proto3" json:"join_eui,omitempty"`
	// The LoRaWAN DevAddr.
	DevAddr              []byte   `protobuf:"bytes,6,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndDeviceIdentifiers) Reset()         { *m = EndDeviceIdentifiers{} }
func (m *EndDeviceIdentifiers) String() string { return proto.CompactTextString(m) }
func (*EndDeviceIdentifiers) ProtoMessage()    {}
func (*EndDeviceIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{2}
}
func (m *EndDeviceIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndDeviceIdentifiers.Unmarshal(m, b)
}
func (m *EndDeviceIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndDeviceIdentifiers.Marshal(b, m, deterministic)
}
func (m *EndDeviceIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndDeviceIdentifiers.Merge(m, src)
}
func (m *EndDeviceIdentifiers) XXX_Size() int {
	return xxx_messageInfo_EndDeviceIdentifiers.Size(m)
}
func (m *EndDeviceIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_EndDeviceIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_EndDeviceIdentifiers proto.InternalMessageInfo

func (m *EndDeviceIdentifiers) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *EndDeviceIdentifiers) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *EndDeviceIdentifiers) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *EndDeviceIdentifiers) GetJoinEui() []byte {
	if m != nil {
		return m.JoinEui
	}
	return nil
}

func (m *EndDeviceIdentifiers) GetDevAddr() []byte {
	if m != nil {
		return m.DevAddr
	}
	return nil
}

type GatewayIdentifiers struct {
	GatewayId string `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// Secondary identifier, which can only be used in specific requests.
	Eui                  []byte   `protobuf:"bytes,2,opt,name=eui,proto3" json:"eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayIdentifiers) Reset()         { *m = GatewayIdentifiers{} }
func (m *GatewayIdentifiers) String() string { return proto.CompactTextString(m) }
func (*GatewayIdentifiers) ProtoMessage()    {}
func (*GatewayIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{3}
}
func (m *GatewayIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayIdentifiers.Unmarshal(m, b)
}
func (m *GatewayIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayIdentifiers.Marshal(b, m, deterministic)
}
func (m *GatewayIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayIdentifiers.Merge(m, src)
}
func (m *GatewayIdentifiers) XXX_Size() int {
	return xxx_messageInfo_GatewayIdentifiers.Size(m)
}
func (m *GatewayIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayIdentifiers proto.InternalMessageInfo

func (m *GatewayIdentifiers) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

func (m *GatewayIdentifiers) GetEui() []byte {
	if m != nil {
		return m.Eui
	}
	return nil
}

type OrganizationIdentifiers struct {
	// This ID shares namespace with user IDs.
	OrganizationId       string   `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrganizationIdentifiers) Reset()         { *m = OrganizationIdentifiers{} }
func (m *OrganizationIdentifiers) String() string { return proto.CompactTextString(m) }
func (*OrganizationIdentifiers) ProtoMessage()    {}
func (*OrganizationIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{4}
}
func (m *OrganizationIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationIdentifiers.Unmarshal(m, b)
}
func (m *OrganizationIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationIdentifiers.Marshal(b, m, deterministic)
}
func (m *OrganizationIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationIdentifiers.Merge(m, src)
}
func (m *OrganizationIdentifiers) XXX_Size() int {
	return xxx_messageInfo_OrganizationIdentifiers.Size(m)
}
func (m *OrganizationIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationIdentifiers proto.InternalMessageInfo

func (m *OrganizationIdentifiers) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

type UserIdentifiers struct {
	// This ID shares namespace with organization IDs.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Secondary identifier, which can only be used in specific requests.
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIdentifiers) Reset()         { *m = UserIdentifiers{} }
func (m *UserIdentifiers) String() string { return proto.CompactTextString(m) }
func (*UserIdentifiers) ProtoMessage()    {}
func (*UserIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{5}
}
func (m *UserIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIdentifiers.Unmarshal(m, b)
}
func (m *UserIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIdentifiers.Marshal(b, m, deterministic)
}
func (m *UserIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIdentifiers.Merge(m, src)
}
func (m *UserIdentifiers) XXX_Size() int {
	return xxx_messageInfo_UserIdentifiers.Size(m)
}
func (m *UserIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_UserIdentifiers proto.InternalMessageInfo

func (m *UserIdentifiers) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserIdentifiers) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// OrganizationOrUserIdentifiers contains either organization or user identifiers.
type OrganizationOrUserIdentifiers struct {
	// Types that are valid to be assigned to Ids:
	//	*OrganizationOrUserIdentifiers_OrganizationIds
	//	*OrganizationOrUserIdentifiers_UserIds
	Ids                  isOrganizationOrUserIdentifiers_Ids `protobuf_oneof:"ids"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *OrganizationOrUserIdentifiers) Reset()         { *m = OrganizationOrUserIdentifiers{} }
func (m *OrganizationOrUserIdentifiers) String() string { return proto.CompactTextString(m) }
func (*OrganizationOrUserIdentifiers) ProtoMessage()    {}
func (*OrganizationOrUserIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{6}
}
func (m *OrganizationOrUserIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationOrUserIdentifiers.Unmarshal(m, b)
}
func (m *OrganizationOrUserIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationOrUserIdentifiers.Marshal(b, m, deterministic)
}
func (m *OrganizationOrUserIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationOrUserIdentifiers.Merge(m, src)
}
func (m *OrganizationOrUserIdentifiers) XXX_Size() int {
	return xxx_messageInfo_OrganizationOrUserIdentifiers.Size(m)
}
func (m *OrganizationOrUserIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationOrUserIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationOrUserIdentifiers proto.InternalMessageInfo

type isOrganizationOrUserIdentifiers_Ids interface {
	isOrganizationOrUserIdentifiers_Ids()
}

type OrganizationOrUserIdentifiers_OrganizationIds struct {
	OrganizationIds *OrganizationIdentifiers `protobuf:"bytes,1,opt,name=organization_ids,json=organizationIds,proto3,oneof" json:"organization_ids,omitempty"`
}
type OrganizationOrUserIdentifiers_UserIds struct {
	UserIds *UserIdentifiers `protobuf:"bytes,2,opt,name=user_ids,json=userIds,proto3,oneof" json:"user_ids,omitempty"`
}

func (*OrganizationOrUserIdentifiers_OrganizationIds) isOrganizationOrUserIdentifiers_Ids() {}
func (*OrganizationOrUserIdentifiers_UserIds) isOrganizationOrUserIdentifiers_Ids()         {}

func (m *OrganizationOrUserIdentifiers) GetIds() isOrganizationOrUserIdentifiers_Ids {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *OrganizationOrUserIdentifiers) GetOrganizationIds() *OrganizationIdentifiers {
	if x, ok := m.GetIds().(*OrganizationOrUserIdentifiers_OrganizationIds); ok {
		return x.OrganizationIds
	}
	return nil
}

func (m *OrganizationOrUserIdentifiers) GetUserIds() *UserIdentifiers {
	if x, ok := m.GetIds().(*OrganizationOrUserIdentifiers_UserIds); ok {
		return x.UserIds
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OrganizationOrUserIdentifiers) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OrganizationOrUserIdentifiers_OrganizationIds)(nil),
		(*OrganizationOrUserIdentifiers_UserIds)(nil),
	}
}

// EntityIdentifiers contains one of the possible entity identifiers.
type EntityIdentifiers struct {
	// Types that are valid to be assigned to Ids:
	//	*EntityIdentifiers_ApplicationIds
	//	*EntityIdentifiers_ClientIds
	//	*EntityIdentifiers_DeviceIds
	//	*EntityIdentifiers_GatewayIds
	//	*EntityIdentifiers_OrganizationIds
	//	*EntityIdentifiers_UserIds
	Ids                  isEntityIdentifiers_Ids `protobuf_oneof:"ids"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EntityIdentifiers) Reset()         { *m = EntityIdentifiers{} }
func (m *EntityIdentifiers) String() string { return proto.CompactTextString(m) }
func (*EntityIdentifiers) ProtoMessage()    {}
func (*EntityIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{7}
}
func (m *EntityIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityIdentifiers.Unmarshal(m, b)
}
func (m *EntityIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityIdentifiers.Marshal(b, m, deterministic)
}
func (m *EntityIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityIdentifiers.Merge(m, src)
}
func (m *EntityIdentifiers) XXX_Size() int {
	return xxx_messageInfo_EntityIdentifiers.Size(m)
}
func (m *EntityIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_EntityIdentifiers proto.InternalMessageInfo

type isEntityIdentifiers_Ids interface {
	isEntityIdentifiers_Ids()
}

type EntityIdentifiers_ApplicationIds struct {
	ApplicationIds *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3,oneof" json:"application_ids,omitempty"`
}
type EntityIdentifiers_ClientIds struct {
	ClientIds *ClientIdentifiers `protobuf:"bytes,2,opt,name=client_ids,json=clientIds,proto3,oneof" json:"client_ids,omitempty"`
}
type EntityIdentifiers_DeviceIds struct {
	DeviceIds *EndDeviceIdentifiers `protobuf:"bytes,3,opt,name=device_ids,json=deviceIds,proto3,oneof" json:"device_ids,omitempty"`
}
type EntityIdentifiers_GatewayIds struct {
	GatewayIds *GatewayIdentifiers `protobuf:"bytes,4,opt,name=gateway_ids,json=gatewayIds,proto3,oneof" json:"gateway_ids,omitempty"`
}
type EntityIdentifiers_OrganizationIds struct {
	OrganizationIds *OrganizationIdentifiers `protobuf:"bytes,5,opt,name=organization_ids,json=organizationIds,proto3,oneof" json:"organization_ids,omitempty"`
}
type EntityIdentifiers_UserIds struct {
	UserIds *UserIdentifiers `protobuf:"bytes,6,opt,name=user_ids,json=userIds,proto3,oneof" json:"user_ids,omitempty"`
}

func (*EntityIdentifiers_ApplicationIds) isEntityIdentifiers_Ids()  {}
func (*EntityIdentifiers_ClientIds) isEntityIdentifiers_Ids()       {}
func (*EntityIdentifiers_DeviceIds) isEntityIdentifiers_Ids()       {}
func (*EntityIdentifiers_GatewayIds) isEntityIdentifiers_Ids()      {}
func (*EntityIdentifiers_OrganizationIds) isEntityIdentifiers_Ids() {}
func (*EntityIdentifiers_UserIds) isEntityIdentifiers_Ids()         {}

func (m *EntityIdentifiers) GetIds() isEntityIdentifiers_Ids {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *EntityIdentifiers) GetApplicationIds() *ApplicationIdentifiers {
	if x, ok := m.GetIds().(*EntityIdentifiers_ApplicationIds); ok {
		return x.ApplicationIds
	}
	return nil
}

func (m *EntityIdentifiers) GetClientIds() *ClientIdentifiers {
	if x, ok := m.GetIds().(*EntityIdentifiers_ClientIds); ok {
		return x.ClientIds
	}
	return nil
}

func (m *EntityIdentifiers) GetDeviceIds() *EndDeviceIdentifiers {
	if x, ok := m.GetIds().(*EntityIdentifiers_DeviceIds); ok {
		return x.DeviceIds
	}
	return nil
}

func (m *EntityIdentifiers) GetGatewayIds() *GatewayIdentifiers {
	if x, ok := m.GetIds().(*EntityIdentifiers_GatewayIds); ok {
		return x.GatewayIds
	}
	return nil
}

func (m *EntityIdentifiers) GetOrganizationIds() *OrganizationIdentifiers {
	if x, ok := m.GetIds().(*EntityIdentifiers_OrganizationIds); ok {
		return x.OrganizationIds
	}
	return nil
}

func (m *EntityIdentifiers) GetUserIds() *UserIdentifiers {
	if x, ok := m.GetIds().(*EntityIdentifiers_UserIds); ok {
		return x.UserIds
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EntityIdentifiers) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EntityIdentifiers_ApplicationIds)(nil),
		(*EntityIdentifiers_ClientIds)(nil),
		(*EntityIdentifiers_DeviceIds)(nil),
		(*EntityIdentifiers_GatewayIds)(nil),
		(*EntityIdentifiers_OrganizationIds)(nil),
		(*EntityIdentifiers_UserIds)(nil),
	}
}

// Identifies an end device model with version information.
type EndDeviceVersionIdentifiers struct {
	BrandId         string `protobuf:"bytes,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	ModelId         string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	HardwareVersion string `protobuf:"bytes,3,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	FirmwareVersion string `protobuf:"bytes,4,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	BandId          string `protobuf:"bytes,5,opt,name=band_id,json=bandId,proto3" json:"band_id,omitempty"`
	// VendorID managed by the LoRa Alliance, as defined in TR005.
	VendorId uint32 `protobuf:"varint,6,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	// ID of the LoRaWAN end device profile assigned by the vendor.
	VendorProfileId      uint32   `protobuf:"varint,7,opt,name=vendor_profile_id,json=vendorProfileId,proto3" json:"vendor_profile_id,omitempty"`
	SerialNumber         string   `protobuf:"bytes,8,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndDeviceVersionIdentifiers) Reset()         { *m = EndDeviceVersionIdentifiers{} }
func (m *EndDeviceVersionIdentifiers) String() string { return proto.CompactTextString(m) }
func (*EndDeviceVersionIdentifiers) ProtoMessage()    {}
func (*EndDeviceVersionIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{8}
}
func (m *EndDeviceVersionIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndDeviceVersionIdentifiers.Unmarshal(m, b)
}
func (m *EndDeviceVersionIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndDeviceVersionIdentifiers.Marshal(b, m, deterministic)
}
func (m *EndDeviceVersionIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndDeviceVersionIdentifiers.Merge(m, src)
}
func (m *EndDeviceVersionIdentifiers) XXX_Size() int {
	return xxx_messageInfo_EndDeviceVersionIdentifiers.Size(m)
}
func (m *EndDeviceVersionIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_EndDeviceVersionIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_EndDeviceVersionIdentifiers proto.InternalMessageInfo

func (m *EndDeviceVersionIdentifiers) GetBrandId() string {
	if m != nil {
		return m.BrandId
	}
	return ""
}

func (m *EndDeviceVersionIdentifiers) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *EndDeviceVersionIdentifiers) GetHardwareVersion() string {
	if m != nil {
		return m.HardwareVersion
	}
	return ""
}

func (m *EndDeviceVersionIdentifiers) GetFirmwareVersion() string {
	if m != nil {
		return m.FirmwareVersion
	}
	return ""
}

func (m *EndDeviceVersionIdentifiers) GetBandId() string {
	if m != nil {
		return m.BandId
	}
	return ""
}

func (m *EndDeviceVersionIdentifiers) GetVendorId() uint32 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *EndDeviceVersionIdentifiers) GetVendorProfileId() uint32 {
	if m != nil {
		return m.VendorProfileId
	}
	return 0
}

func (m *EndDeviceVersionIdentifiers) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

// Identifies a Network Server.
type NetworkIdentifiers struct {
	// LoRa Alliance NetID.
	NetId []byte `protobuf:"bytes,1,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	// Optional tenant identifier for multi-tenant deployments.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Cluster identifier of the Network Server.
	ClusterId string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Cluster address of the Network Server.
	ClusterAddress string `protobuf:"bytes,4,opt,name=cluster_address,json=clusterAddress,proto3" json:"cluster_address,omitempty"`
	// Optional tenant address for multi-tenant deployments.
	TenantAddress        string   `protobuf:"bytes,5,opt,name=tenant_address,json=tenantAddress,proto3" json:"tenant_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkIdentifiers) Reset()         { *m = NetworkIdentifiers{} }
func (m *NetworkIdentifiers) String() string { return proto.CompactTextString(m) }
func (*NetworkIdentifiers) ProtoMessage()    {}
func (*NetworkIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da1fbfdea4d7423, []int{9}
}
func (m *NetworkIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkIdentifiers.Unmarshal(m, b)
}
func (m *NetworkIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkIdentifiers.Marshal(b, m, deterministic)
}
func (m *NetworkIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkIdentifiers.Merge(m, src)
}
func (m *NetworkIdentifiers) XXX_Size() int {
	return xxx_messageInfo_NetworkIdentifiers.Size(m)
}
func (m *NetworkIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkIdentifiers proto.InternalMessageInfo

func (m *NetworkIdentifiers) GetNetId() []byte {
	if m != nil {
		return m.NetId
	}
	return nil
}

func (m *NetworkIdentifiers) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *NetworkIdentifiers) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *NetworkIdentifiers) GetClusterAddress() string {
	if m != nil {
		return m.ClusterAddress
	}
	return ""
}

func (m *NetworkIdentifiers) GetTenantAddress() string {
	if m != nil {
		return m.TenantAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*ApplicationIdentifiers)(nil), "ttn.lorawan.v3.ApplicationIdentifiers")
	golang_proto.RegisterType((*ApplicationIdentifiers)(nil), "ttn.lorawan.v3.ApplicationIdentifiers")
	proto.RegisterType((*ClientIdentifiers)(nil), "ttn.lorawan.v3.ClientIdentifiers")
	golang_proto.RegisterType((*ClientIdentifiers)(nil), "ttn.lorawan.v3.ClientIdentifiers")
	proto.RegisterType((*EndDeviceIdentifiers)(nil), "ttn.lorawan.v3.EndDeviceIdentifiers")
	golang_proto.RegisterType((*EndDeviceIdentifiers)(nil), "ttn.lorawan.v3.EndDeviceIdentifiers")
	proto.RegisterType((*GatewayIdentifiers)(nil), "ttn.lorawan.v3.GatewayIdentifiers")
	golang_proto.RegisterType((*GatewayIdentifiers)(nil), "ttn.lorawan.v3.GatewayIdentifiers")
	proto.RegisterType((*OrganizationIdentifiers)(nil), "ttn.lorawan.v3.OrganizationIdentifiers")
	golang_proto.RegisterType((*OrganizationIdentifiers)(nil), "ttn.lorawan.v3.OrganizationIdentifiers")
	proto.RegisterType((*UserIdentifiers)(nil), "ttn.lorawan.v3.UserIdentifiers")
	golang_proto.RegisterType((*UserIdentifiers)(nil), "ttn.lorawan.v3.UserIdentifiers")
	proto.RegisterType((*OrganizationOrUserIdentifiers)(nil), "ttn.lorawan.v3.OrganizationOrUserIdentifiers")
	golang_proto.RegisterType((*OrganizationOrUserIdentifiers)(nil), "ttn.lorawan.v3.OrganizationOrUserIdentifiers")
	proto.RegisterType((*EntityIdentifiers)(nil), "ttn.lorawan.v3.EntityIdentifiers")
	golang_proto.RegisterType((*EntityIdentifiers)(nil), "ttn.lorawan.v3.EntityIdentifiers")
	proto.RegisterType((*EndDeviceVersionIdentifiers)(nil), "ttn.lorawan.v3.EndDeviceVersionIdentifiers")
	golang_proto.RegisterType((*EndDeviceVersionIdentifiers)(nil), "ttn.lorawan.v3.EndDeviceVersionIdentifiers")
	proto.RegisterType((*NetworkIdentifiers)(nil), "ttn.lorawan.v3.NetworkIdentifiers")
	golang_proto.RegisterType((*NetworkIdentifiers)(nil), "ttn.lorawan.v3.NetworkIdentifiers")
}

func init() {
	proto.RegisterFile("lorawan-stack/api/identifiers.proto", fileDescriptor_6da1fbfdea4d7423)
}
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/identifiers.proto", fileDescriptor_6da1fbfdea4d7423)
}

var fileDescriptor_6da1fbfdea4d7423 = []byte{
	// 1246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcf, 0x6f, 0x1b, 0xc5,
	0x17, 0xcf, 0xae, 0x7f, 0xad, 0x27, 0x4d, 0x9c, 0xae, 0xbe, 0xfa, 0xd6, 0x49, 0xa1, 0xa4, 0x26,
	0xb4, 0xa1, 0xc2, 0x5e, 0xd7, 0x6e, 0x29, 0x54, 0x48, 0xad, 0xb7, 0x71, 0x1b, 0x57, 0x22, 0x2d,
	0xab, 0x16, 0x01, 0x55, 0x1b, 0x8d, 0x77, 0x26, 0xeb, 0x69, 0xd7, 0xb3, 0xab, 0x99, 0xb1, 0xd3,
	0xb4, 0x20, 0x21, 0x8e, 0x1c, 0x7b, 0xe4, 0x02, 0xe2, 0x98, 0xbf, 0x82, 0x2b, 0x27, 0xe0, 0x80,
	0x44, 0x0f, 0x9c, 0x38, 0x20, 0x21, 0xb8, 0x14, 0x21, 0xa1, 0x9c, 0xd0, 0xce, 0xae, 0x93, 0xf5,
	0x3a, 0x05, 0x1c, 0x12, 0xa9, 0x87, 0xde, 0x76, 0x67, 0xde, 0xfb, 0xbc, 0x79, 0x9f, 0x37, 0xef,
	0xc7, 0x80, 0x97, 0x5d, 0x8f, 0xc1, 0x75, 0x48, 0xcb, 0x5c, 0x40, 0xfb, 0x9e, 0x01, 0x7d, 0x62,
	0x10, 0x84, 0xa9, 0x20, 0x6b, 0x04, 0x33, 0x5e, 0xf1, 0x99, 0x27, 0x3c, 0x7d, 0x5a, 0x08, 0x5a,
	0x89, 0x04, 0x2b, 0xfd, 0xfa, 0x5c, 0xc3, 0x21, 0xa2, 0xd3, 0x6b, 0x57, 0x6c, 0xaf, 0x6b, 0x60,
	0xda, 0xf7, 0x36, 0x7c, 0xe6, 0xdd, 0xdf, 0x30, 0xa4, 0xb0, 0x5d, 0x76, 0x30, 0x2d, 0xf7, 0xa1,
	0x4b, 0x10, 0x14, 0xd8, 0x18, 0xf9, 0x08, 0x21, 0xe7, 0xca, 0x31, 0x08, 0xc7, 0x73, 0xbc, 0x50,
	0xb9, 0xdd, 0x5b, 0x93, 0x7f, 0xf2, 0x47, 0x7e, 0x45, 0xe2, 0x4b, 0x31, 0xf1, 0x1b, 0x1d, 0x7c,
	0xa3, 0x43, 0xa8, 0xc3, 0x5b, 0x14, 0xf5, 0xb8, 0x60, 0x04, 0xf3, 0xb8, 0x69, 0xc7, 0x2b, 0xaf,
	0xb9, 0xd0, 0xe1, 0x06, 0xa4, 0xd4, 0x13, 0x50, 0x10, 0x8f, 0x46, 0x7e, 0xcc, 0x5d, 0x1a, 0x0b,
	0xe5, 0x2e, 0xf7, 0xe8, 0x2e, 0x20, 0x95, 0x98, 0x94, 0xe7, 0x63, 0x0a, 0x7d, 0xd2, 0xaf, 0x19,
	0x9e, 0x2f, 0x65, 0x46, 0xe5, 0x4b, 0x0c, 0xfc, 0xbf, 0xe1, 0xfb, 0x2e, 0xb1, 0xe5, 0x6a, 0x6b,
	0x87, 0x5c, 0x7d, 0x05, 0x4c, 0xc3, 0x9d, 0x9d, 0x55, 0x82, 0x8a, 0xca, 0xbc, 0xb2, 0x98, 0x37,
	0x4f, 0x6e, 0x99, 0x0b, 0xac, 0x54, 0x5c, 0xa8, 0x1d, 0xbb, 0x73, 0x0b, 0x96, 0x1f, 0x54, 0xcb,
	0x6f, 0xde, 0x5e, 0xbc, 0x70, 0xfe, 0x56, 0xf9, 0xf6, 0x85, 0xc1, 0xef, 0xab, 0x0f, 0x6b, 0xaf,
	0x7d, 0xb4, 0x60, 0x4d, 0xc1, 0x38, 0xf0, 0x79, 0xed, 0xc9, 0xe6, 0x6c, 0x5a, 0x53, 0x66, 0x94,
	0x92, 0x0d, 0x0e, 0x5f, 0x72, 0x09, 0xa6, 0x22, 0x6e, 0x6e, 0x09, 0xe4, 0x6d, 0xb9, 0xb8, 0x07,
	0x4b, 0x9a, 0x1d, 0xc1, 0xc5, 0x8c, 0x7c, 0x0e, 0xc0, 0xff, 0x9a, 0x14, 0x2d, 0xe1, 0x3e, 0xb1,
	0x71, 0xc2, 0x10, 0x92, 0x8b, 0x7b, 0x31, 0x84, 0x22, 0x38, 0xfd, 0x7d, 0x50, 0x18, 0x66, 0x87,
	0x17, 0xd5, 0x79, 0x65, 0x71, 0xb2, 0x76, 0xa2, 0x32, 0x7c, 0x1d, 0x2b, 0xbb, 0xd3, 0x6b, 0x6a,
	0x5b, 0x66, 0xe6, 0x53, 0x45, 0x9d, 0x51, 0xac, 0xe9, 0x21, 0x9e, 0xb8, 0xfe, 0xbb, 0x0a, 0x72,
	0x08, 0xf7, 0x57, 0x71, 0x8f, 0x14, 0xd3, 0xf3, 0xca, 0xe2, 0x21, 0xf3, 0xb1, 0xfa, 0xa8, 0x71,
	0xfc, 0xaa, 0x5e, 0x3a, 0x57, 0x35, 0xeb, 0x4b, 0x67, 0xcf, 0x35, 0x97, 0xaa, 0xd5, 0x6a, 0xc3,
	0xbc, 0xb4, 0x54, 0xfa, 0x4c, 0x55, 0x72, 0x5f, 0xaa, 0xd9, 0xe0, 0x82, 0x50, 0x67, 0xcb, 0xcc,
	0x3e, 0x48, 0x77, 0x34, 0x5f, 0xf9, 0x65, 0x73, 0xf6, 0x13, 0x05, 0x5c, 0x70, 0xbc, 0x8a, 0xe8,
	0x60, 0x21, 0xaf, 0x51, 0x85, 0x62, 0xb1, 0xee, 0xb1, 0x7b, 0xc6, 0x70, 0x42, 0xf5, 0xeb, 0x86,
	0x7f, 0xcf, 0x31, 0xc4, 0x86, 0x8f, 0x79, 0xe5, 0x6d, 0xc8, 0x78, 0x07, 0xba, 0xcb, 0xcd, 0xf7,
	0xcc, 0x0d, 0x81, 0xb9, 0x3e, 0x36, 0xc0, 0x4d, 0xda, 0x0d, 0x21, 0xde, 0x90, 0x00, 0x4f, 0x36,
	0x67, 0xbf, 0x50, 0xe6, 0x56, 0xfe, 0x1d, 0x8a, 0xdd, 0x45, 0x86, 0x10, 0xb4, 0xec, 0xae, 0x97,
	0x6d, 0x97, 0x18, 0x76, 0x8f, 0x0b, 0xaf, 0x2b, 0x33, 0xa5, 0xb2, 0x82, 0xd7, 0x43, 0xc0, 0xcb,
	0x2e, 0x74, 0x4a, 0xff, 0x1d, 0xef, 0x0a, 0x16, 0xcd, 0xfb, 0xd0, 0x16, 0x12, 0xd3, 0xca, 0x22,
	0xdc, 0x6f, 0xf6, 0x88, 0xfe, 0x87, 0x0a, 0xb4, 0xbb, 0x1e, 0xa1, 0x92, 0xf6, 0xcc, 0x73, 0xda,
	0x0f, 0x98, 0xf6, 0x5c, 0xc0, 0x75, 0xc0, 0xfb, 0x6f, 0x2a, 0x08, 0xb2, 0x6a, 0x15, 0x22, 0xc4,
	0x8a, 0x59, 0xc9, 0xfb, 0x77, 0xea, 0xa3, 0xc6, 0xec, 0x55, 0x50, 0xaa, 0xbd, 0xfe, 0x74, 0xbe,
	0xd3, 0xcf, 0x00, 0xdf, 0x67, 0xf6, 0x9b, 0xef, 0x33, 0x07, 0xc8, 0x37, 0xc2, 0xfd, 0x06, 0x42,
	0x2c, 0x56, 0x21, 0xbf, 0x4f, 0x01, 0xfd, 0x0a, 0x14, 0x78, 0x1d, 0x6e, 0xc4, 0xeb, 0xe3, 0x65,
	0x00, 0x9c, 0x70, 0x75, 0x0f, 0x05, 0x32, 0xef, 0x0c, 0x00, 0xf5, 0x5f, 0x55, 0x90, 0x0a, 0x72,
	0x49, 0x7d, 0x9e, 0x4b, 0x07, 0x9c, 0x4b, 0x01, 0xcd, 0xb1, 0xb8, 0xf6, 0xc0, 0x91, 0x6b, 0xcc,
	0x81, 0x94, 0x3c, 0x18, 0xe9, 0xe9, 0xd7, 0x41, 0xc1, 0x8b, 0x6d, 0xed, 0x21, 0xc0, 0xd3, 0xde,
	0x10, 0x74, 0xcc, 0xec, 0x43, 0x50, 0xb8, 0xc9, 0x31, 0x8b, 0x9b, 0xbb, 0x08, 0x72, 0x3d, 0x8e,
	0xd9, 0x78, 0x66, 0x4e, 0x07, 0x66, 0xb2, 0x3d, 0x09, 0xa5, 0xbf, 0x00, 0x32, 0xb8, 0x0b, 0x89,
	0x2b, 0x6f, 0x51, 0xde, 0xcc, 0x3e, 0xd9, 0x9c, 0x55, 0x17, 0x15, 0x2b, 0x5c, 0x8c, 0x19, 0xff,
	0x5a, 0x01, 0x2f, 0xc6, 0x9d, 0xbe, 0xc6, 0x92, 0x67, 0xb9, 0x01, 0x66, 0x12, 0xae, 0x73, 0x79,
	0xa8, 0xc9, 0xda, 0xc9, 0x64, 0xc7, 0x7e, 0x0a, 0x7b, 0xcb, 0x13, 0x56, 0x61, 0xd8, 0x7b, 0xae,
	0xbf, 0x05, 0xb4, 0xc8, 0xc3, 0x41, 0xff, 0x7f, 0x29, 0x89, 0x96, 0x38, 0xc8, 0xf2, 0x84, 0x95,
	0x0b, 0x9d, 0xe3, 0x3b, 0xe7, 0x37, 0x01, 0x48, 0x11, 0xc4, 0xf5, 0xd4, 0x9f, 0xa6, 0x52, 0xfa,
	0x21, 0x05, 0x0e, 0x37, 0xa9, 0x20, 0x62, 0x28, 0x2d, 0xdf, 0x19, 0x1d, 0x38, 0x94, 0x71, 0x06,
	0x8e, 0xe5, 0x89, 0x91, 0x41, 0xc3, 0x04, 0x60, 0x7b, 0xe4, 0x1a, 0x1c, 0xff, 0x78, 0x12, 0x6d,
	0x64, 0x52, 0x5b, 0x9e, 0xb0, 0xf2, 0x83, 0x79, 0x8b, 0xeb, 0x4d, 0x00, 0xb6, 0xa7, 0x29, 0x5e,
	0x4c, 0x49, 0x8c, 0x85, 0x24, 0xc6, 0x6e, 0x73, 0x58, 0x00, 0x33, 0x98, 0xa6, 0x02, 0x98, 0xc9,
	0x9d, 0xa2, 0xc3, 0xe5, 0xd8, 0x33, 0x59, 0x2b, 0x25, 0x71, 0x46, 0xab, 0xd5, 0xf2, 0x84, 0x05,
	0xb6, 0x4b, 0xce, 0xee, 0x41, 0xce, 0xec, 0x6b, 0x90, 0xb3, 0xe3, 0x06, 0x79, 0x28, 0xb4, 0x8f,
	0x53, 0xe0, 0xe8, 0x36, 0x19, 0xef, 0x62, 0xc6, 0x13, 0xf9, 0xd9, 0x04, 0x5a, 0x9b, 0x41, 0x8a,
	0x76, 0x32, 0xe6, 0xd4, 0x96, 0x79, 0x92, 0xbd, 0xf2, 0xcf, 0x89, 0xf9, 0xad, 0xa2, 0x58, 0x39,
	0xa9, 0xdb, 0x42, 0x01, 0x4c, 0xd7, 0x43, 0xd8, 0x0d, 0x60, 0xd4, 0xf1, 0x61, 0xa4, 0x6e, 0x0b,
	0xe9, 0x35, 0x30, 0xd3, 0x81, 0x0c, 0xad, 0x43, 0x86, 0x57, 0xfb, 0xe1, 0x61, 0x65, 0x84, 0xf3,
	0x66, 0x6e, 0xcb, 0x4c, 0x33, 0xb5, 0x38, 0x6f, 0x15, 0x06, 0x02, 0x91, 0x33, 0x81, 0xce, 0x1a,
	0x61, 0xdd, 0x21, 0x9d, 0x74, 0x42, 0x67, 0x20, 0x30, 0xd0, 0x99, 0x07, 0xb9, 0x76, 0xe4, 0x74,
	0x66, 0x58, 0x34, 0xdb, 0x0e, 0x1d, 0x3a, 0x0a, 0xf2, 0x7d, 0x4c, 0x91, 0x27, 0x4b, 0x49, 0x10,
	0x82, 0x29, 0x4b, 0x0b, 0x17, 0x5a, 0x48, 0x3f, 0x05, 0x0e, 0x47, 0x9b, 0x3e, 0xf3, 0xd6, 0x88,
	0x2b, 0x07, 0xfb, 0x9c, 0x14, 0x2a, 0x84, 0x1b, 0xd7, 0xc3, 0xf5, 0x16, 0xd2, 0xaf, 0x81, 0x29,
	0x8e, 0x19, 0x81, 0xee, 0x2a, 0xed, 0x75, 0xdb, 0x98, 0x15, 0xb5, 0xb1, 0xe9, 0x39, 0x14, 0x02,
	0xac, 0x48, 0xfd, 0x58, 0x09, 0xfa, 0x31, 0x0d, 0xf4, 0x95, 0xb0, 0x96, 0xc7, 0x43, 0xfa, 0xb3,
	0x0a, 0xb2, 0x14, 0x6f, 0xbf, 0x6a, 0x0e, 0x99, 0xdf, 0xa8, 0x8f, 0x1a, 0x47, 0xae, 0x6a, 0xa5,
	0x6a, 0xb5, 0x5a, 0x3d, 0x5d, 0xdf, 0xad, 0xff, 0xa5, 0x9e, 0x81, 0xfe, 0x57, 0xdf, 0xef, 0xfe,
	0x57, 0x3f, 0xb8, 0xfe, 0x97, 0xa1, 0x58, 0xb4, 0x90, 0x7e, 0x05, 0xe4, 0x05, 0xa6, 0x30, 0x7c,
	0x41, 0x26, 0xae, 0xfd, 0xf1, 0xbf, 0x8f, 0xeb, 0x87, 0x77, 0x16, 0x2c, 0x2d, 0x54, 0x6e, 0x21,
	0xfd, 0x44, 0x50, 0x17, 0x7b, 0x5c, 0x84, 0x9d, 0x6b, 0xe8, 0xc6, 0x5f, 0x0c, 0x6a, 0x9f, 0xdc,
	0x6a, 0x21, 0xfd, 0x34, 0x28, 0x0c, 0xe4, 0x82, 0xe9, 0x15, 0x73, 0x1e, 0x5d, 0xf5, 0xe0, 0x6d,
	0xc7, 0x52, 0xc5, 0x8f, 0x55, 0x6b, 0x3a, 0x12, 0x68, 0x84, 0xfb, 0xba, 0x01, 0xa6, 0xa3, 0x33,
	0x0e, 0x34, 0x32, 0x09, 0x8d, 0xa9, 0x70, 0x3f, 0x52, 0xd8, 0xbe, 0x5f, 0x13, 0xe6, 0xd9, 0xaf,
	0x7e, 0x3a, 0xa6, 0x7c, 0x60, 0x8c, 0x11, 0x51, 0x41, 0xfd, 0x76, 0x3b, 0x2b, 0xdf, 0xf9, 0xf5,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xee, 0xbd, 0x75, 0x68, 0x4b, 0x11, 0x00, 0x00,
}
