// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/oauth_services.proto

package ttnpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("lorawan-stack/api/oauth_services.proto", fileDescriptor_10930ff381158870)
}
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/oauth_services.proto", fileDescriptor_10930ff381158870)
}

var fileDescriptor_10930ff381158870 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x3f, 0x68, 0x14, 0x41,
	0x14, 0xc6, 0x67, 0x44, 0x53, 0xac, 0x60, 0x31, 0x85, 0xc5, 0xa9, 0x0f, 0xbc, 0x42, 0xf4, 0xd4,
	0x19, 0xf1, 0xec, 0xe5, 0xfc, 0x2f, 0xfe, 0x83, 0x68, 0x65, 0x13, 0xf6, 0xee, 0x26, 0x7b, 0xc3,
	0x9d, 0x33, 0xeb, 0xce, 0xdb, 0x0b, 0xf1, 0x38, 0x08, 0x56, 0x29, 0x05, 0x1b, 0x6d, 0xc4, 0x46,
	0x4c, 0x23, 0x04, 0x6c, 0x52, 0xa6, 0x4c, 0x19, 0xb0, 0x49, 0x99, 0x9d, 0xb5, 0x48, 0x99, 0x32,
	0xa5, 0xec, 0xec, 0x46, 0x3c, 0xf1, 0xf0, 0x40, 0x8b, 0x65, 0xdf, 0xee, 0xfb, 0xbe, 0x99, 0xdf,
	0x7c, 0x8f, 0x09, 0xce, 0x0d, 0x4c, 0x12, 0x2e, 0x85, 0xfa, 0xb2, 0xc5, 0xb0, 0xd3, 0x17, 0x61,
	0xac, 0x84, 0x09, 0x53, 0xec, 0x2d, 0x58, 0x99, 0x0c, 0x55, 0x47, 0x5a, 0x1e, 0x27, 0x06, 0x0d,
	0x3b, 0x81, 0xa8, 0x79, 0xa5, 0xe5, 0xc3, 0x66, 0xed, 0x74, 0x64, 0x4c, 0x34, 0x90, 0xde, 0x10,
	0x6a, 0x6d, 0x30, 0x44, 0x65, 0x74, 0xa5, 0xae, 0x9d, 0xaa, 0xba, 0xfe, 0xab, 0x9d, 0x2e, 0x0a,
	0xf9, 0x22, 0xc6, 0xe5, 0xaa, 0x79, 0x66, 0xca, 0x96, 0x65, 0xfb, 0xea, 0xd7, 0x63, 0x41, 0xed,
	0x49, 0x2b, 0xc5, 0x5e, 0xf1, 0x98, 0x44, 0xbd, 0xf2, 0x2b, 0xcf, 0xcb, 0x48, 0x59, 0x4c, 0x96,
	0xd9, 0x7b, 0x1a, 0x1c, 0x7d, 0xa8, 0x2c, 0xb2, 0x6b, 0x7c, 0x12, 0x89, 0x17, 0x7f, 0xbd, 0xf1,
	0xe6, 0x40, 0x49, 0x8d, 0x13, 0x76, 0x3b, 0x2f, 0x5f, 0xa6, 0xd2, 0x62, 0xed, 0xc2, 0xef, 0xae,
	0xa9, 0x8e, 0xfa, 0x95, 0xd7, 0xdf, 0xbe, 0xbf, 0x3d, 0xd2, 0x60, 0xe7, 0x45, 0x6a, 0x65, 0x62,
	0xc5, 0xa8, 0x78, 0x2d, 0xa8, 0xae, 0xe5, 0x55, 0x31, 0x16, 0xe1, 0x84, 0x83, 0x7d, 0xa1, 0x41,
	0x50, 0x50, 0x3c, 0x33, 0x7d, 0xa9, 0x2d, 0xbb, 0x34, 0x95, 0xb0, 0xd5, 0xe9, 0x48, 0x6b, 0x4b,
	0xd9, 0x21, 0xd9, 0xd9, 0x3f, 0x92, 0xfd, 0xaa, 0xac, 0x3f, 0xf6, 0x44, 0xf7, 0xd8, 0x9d, 0x59,
	0x89, 0xc4, 0xa8, 0xe3, 0x4f, 0xe6, 0x35, 0x3f, 0xcb, 0xb1, 0xc0, 0x12, 0xf0, 0x03, 0x0d, 0xe6,
	0x6e, 0xc9, 0x81, 0x44, 0xc9, 0x9a, 0xb3, 0xe6, 0x72, 0xbf, 0x2b, 0x35, 0xaa, 0x45, 0x25, 0x13,
	0x5b, 0x3b, 0xc9, 0xcb, 0x39, 0xf3, 0xc3, 0x39, 0xf3, 0xdb, 0xc5, 0x9c, 0xeb, 0x77, 0x3d, 0x67,
	0xab, 0x71, 0xfd, 0x1f, 0x39, 0xd9, 0x67, 0x1a, 0x1c, 0x2f, 0x01, 0x7d, 0x02, 0xec, 0xe2, 0xdf,
	0x32, 0x9a, 0x85, 0xee, 0xa9, 0xa7, 0x7b, 0xd4, 0x78, 0xf0, 0x7f, 0x52, 0x14, 0x23, 0xd5, 0x1d,
	0xdf, 0xf8, 0x44, 0xb7, 0x32, 0xa0, 0xdb, 0x19, 0xd0, 0x9d, 0x0c, 0xc8, 0x6e, 0x06, 0x64, 0x2f,
	0x03, 0xb2, 0x9f, 0x01, 0x39, 0xc8, 0x80, 0xae, 0x38, 0xa0, 0xab, 0x0e, 0xc8, 0x9a, 0x03, 0xba,
	0xee, 0x80, 0x6c, 0x38, 0x20, 0x9b, 0x0e, 0xc8, 0x96, 0x03, 0xba, 0xed, 0x80, 0xee, 0x38, 0x20,
	0xbb, 0x0e, 0xe8, 0x9e, 0x03, 0xb2, 0xef, 0x80, 0x1e, 0x38, 0x20, 0x2b, 0x39, 0x90, 0xd5, 0x1c,
	0xe8, 0x9b, 0x1c, 0xc8, 0xbb, 0x1c, 0xe8, 0xc7, 0x1c, 0xc8, 0x5a, 0x0e, 0x64, 0x3d, 0x07, 0xba,
	0x91, 0x03, 0xdd, 0xcc, 0x81, 0x3e, 0x17, 0x91, 0xe1, 0xd8, 0x93, 0xd8, 0x53, 0x3a, 0xb2, 0x5c,
	0x4b, 0x5c, 0x32, 0x49, 0x5f, 0x4c, 0x5e, 0xb0, 0x61, 0x53, 0xc4, 0xfd, 0x48, 0x20, 0xea, 0xb8,
	0xdd, 0x9e, 0xf3, 0x61, 0x34, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xdd, 0xba, 0xc8, 0xf8,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OAuthAuthorizationRegistryClient is the client API for OAuthAuthorizationRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OAuthAuthorizationRegistryClient interface {
	List(ctx context.Context, in *ListOAuthClientAuthorizationsRequest, opts ...grpc.CallOption) (*OAuthClientAuthorizations, error)
	ListTokens(ctx context.Context, in *ListOAuthAccessTokensRequest, opts ...grpc.CallOption) (*OAuthAccessTokens, error)
	Delete(ctx context.Context, in *OAuthClientAuthorizationIdentifiers, opts ...grpc.CallOption) (*types.Empty, error)
	DeleteToken(ctx context.Context, in *OAuthAccessTokenIdentifiers, opts ...grpc.CallOption) (*types.Empty, error)
}

type oAuthAuthorizationRegistryClient struct {
	cc *grpc.ClientConn
}

func NewOAuthAuthorizationRegistryClient(cc *grpc.ClientConn) OAuthAuthorizationRegistryClient {
	return &oAuthAuthorizationRegistryClient{cc}
}

func (c *oAuthAuthorizationRegistryClient) List(ctx context.Context, in *ListOAuthClientAuthorizationsRequest, opts ...grpc.CallOption) (*OAuthClientAuthorizations, error) {
	out := new(OAuthClientAuthorizations)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.OAuthAuthorizationRegistry/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthAuthorizationRegistryClient) ListTokens(ctx context.Context, in *ListOAuthAccessTokensRequest, opts ...grpc.CallOption) (*OAuthAccessTokens, error) {
	out := new(OAuthAccessTokens)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.OAuthAuthorizationRegistry/ListTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthAuthorizationRegistryClient) Delete(ctx context.Context, in *OAuthClientAuthorizationIdentifiers, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.OAuthAuthorizationRegistry/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthAuthorizationRegistryClient) DeleteToken(ctx context.Context, in *OAuthAccessTokenIdentifiers, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.OAuthAuthorizationRegistry/DeleteToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthAuthorizationRegistryServer is the server API for OAuthAuthorizationRegistry service.
type OAuthAuthorizationRegistryServer interface {
	List(context.Context, *ListOAuthClientAuthorizationsRequest) (*OAuthClientAuthorizations, error)
	ListTokens(context.Context, *ListOAuthAccessTokensRequest) (*OAuthAccessTokens, error)
	Delete(context.Context, *OAuthClientAuthorizationIdentifiers) (*types.Empty, error)
	DeleteToken(context.Context, *OAuthAccessTokenIdentifiers) (*types.Empty, error)
}

// UnimplementedOAuthAuthorizationRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedOAuthAuthorizationRegistryServer struct {
}

func (*UnimplementedOAuthAuthorizationRegistryServer) List(ctx context.Context, req *ListOAuthClientAuthorizationsRequest) (*OAuthClientAuthorizations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedOAuthAuthorizationRegistryServer) ListTokens(ctx context.Context, req *ListOAuthAccessTokensRequest) (*OAuthAccessTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTokens not implemented")
}
func (*UnimplementedOAuthAuthorizationRegistryServer) Delete(ctx context.Context, req *OAuthClientAuthorizationIdentifiers) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedOAuthAuthorizationRegistryServer) DeleteToken(ctx context.Context, req *OAuthAccessTokenIdentifiers) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteToken not implemented")
}

func RegisterOAuthAuthorizationRegistryServer(s *grpc.Server, srv OAuthAuthorizationRegistryServer) {
	s.RegisterService(&_OAuthAuthorizationRegistry_serviceDesc, srv)
}

func _OAuthAuthorizationRegistry_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOAuthClientAuthorizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthAuthorizationRegistryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.OAuthAuthorizationRegistry/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthAuthorizationRegistryServer).List(ctx, req.(*ListOAuthClientAuthorizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthAuthorizationRegistry_ListTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOAuthAccessTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthAuthorizationRegistryServer).ListTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.OAuthAuthorizationRegistry/ListTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthAuthorizationRegistryServer).ListTokens(ctx, req.(*ListOAuthAccessTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthAuthorizationRegistry_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuthClientAuthorizationIdentifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthAuthorizationRegistryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.OAuthAuthorizationRegistry/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthAuthorizationRegistryServer).Delete(ctx, req.(*OAuthClientAuthorizationIdentifiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthAuthorizationRegistry_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuthAccessTokenIdentifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthAuthorizationRegistryServer).DeleteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.OAuthAuthorizationRegistry/DeleteToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthAuthorizationRegistryServer).DeleteToken(ctx, req.(*OAuthAccessTokenIdentifiers))
	}
	return interceptor(ctx, in, info, handler)
}

var _OAuthAuthorizationRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ttn.lorawan.v3.OAuthAuthorizationRegistry",
	HandlerType: (*OAuthAuthorizationRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _OAuthAuthorizationRegistry_List_Handler,
		},
		{
			MethodName: "ListTokens",
			Handler:    _OAuthAuthorizationRegistry_ListTokens_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _OAuthAuthorizationRegistry_Delete_Handler,
		},
		{
			MethodName: "DeleteToken",
			Handler:    _OAuthAuthorizationRegistry_DeleteToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorawan-stack/api/oauth_services.proto",
}
