// Copyright © 2018 The Things Network Foundation, distributed under the MIT license (see LICENSE file)

package test

import (
	"fmt"
	"time"

	"github.com/TheThingsNetwork/ttn/pkg/identityserver/store"
	"github.com/TheThingsNetwork/ttn/pkg/ttnpb"
	"github.com/smartystreets/assertions"
)

func defaultOrganization(in interface{}) (*ttnpb.Organization, error) {
	if org, ok := in.(store.Organization); ok {
		return org.GetOrganization(), nil
	}

	if org, ok := in.(ttnpb.Organization); ok {
		return &org, nil
	}

	if ptr, ok := in.(*ttnpb.Organization); ok {
		return ptr, nil
	}

	return nil, fmt.Errorf("Expected: '%v' to be of type ttnpb.Organization but it was not", in)
}

// ShouldBeOrganization checks if two Organizations resemble each other.
func ShouldBeOrganization(actual interface{}, expected ...interface{}) string {
	if len(expected) != 1 {
		return fmt.Sprintf("Expected: one organization to match but got %v", len(expected))
	}

	a, s := defaultOrganization(actual)
	if s != nil {
		return s.Error()
	}

	b, s := defaultOrganization(expected[0])
	if s != nil {
		return s.Error()
	}

	return all(
		ShouldBeOrganizationIgnoringAutoFields(a, b),
		assertions.ShouldHappenWithin(a.CreatedAt, time.Millisecond, b.CreatedAt),
		assertions.ShouldHappenWithin(a.UpdatedAt, time.Millisecond, b.UpdatedAt),
	)
}

// ShouldBeOrganizationIgnoringAutoFields checks if two Organizations resemble
// each other without looking at fields that are generated by the database:
// `CreatedAt` and `UpdatedAt`.
func ShouldBeOrganizationIgnoringAutoFields(actual interface{}, expected ...interface{}) string {
	if len(expected) != 1 {
		return fmt.Sprintf("Expected: one organization to match but got %v", len(expected))
	}

	a, s := defaultOrganization(actual)
	if s != nil {
		return s.Error()
	}

	b, s := defaultOrganization(expected[0])
	if s != nil {
		return s.Error()
	}

	return all(
		assertions.ShouldEqual(a.OrganizationID, b.OrganizationID),
		assertions.ShouldEqual(a.Name, b.Name),
		assertions.ShouldEqual(a.Description, b.Description),
		assertions.ShouldEqual(a.URL, b.URL),
		assertions.ShouldEqual(a.Location, b.Location),
		assertions.ShouldEqual(a.Email, b.Email),
	)
}
