// Copyright © 2019 The Things Network Foundation, The Things Industries B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package blacklist

var builtin = New(
	// Staff
	"abuse",
	"admin",
	"administration",
	"administrator",
	"administrators",
	"admins",
	"billing",
	"demo",
	"editor",
	"editors",
	"guest",
	"guests",
	"info",
	"marketplace",
	"master",
	"masters",
	"me",
	"member",
	"members",
	"moderator",
	"moderators",
	"myself",
	"owner",
	"owners",
	"partners",
	"root",
	"sales",
	"security",
	"self",
	"staff",
	"super",
	"superuser",
	"support",
	"sysadmin",
	"thethings",
	"things",
	"this",
	"tti",
	"ttn",
	"user",
	"users",
	"webmaster",

	// Reserved for subdomains
	"about",
	"account",
	"alerts",
	"alpha",
	"analytics",
	"app",
	"application",
	"applications",
	"apps",
	"assets",
	"beta",
	"blog",
	"carreers",
	"cdn",
	"client",
	"clients",
	"community",
	"compare",
	"conference",
	"contact",
	"customers",
	"dev",
	"dns",
	"doc",
	"docs",
	"events",
	"example",
	"examples",
	"extension",
	"extensions",
	"faq",
	"feedback",
	"forum",
	"forums",
	"gateway",
	"gateways",
	"git",
	"gtw",
	"gtws",
	"help",
	"home",
	"homes",
	"http",
	"https",
	"id",
	"identity",
	"join",
	"learn",
	"local",
	"localdomain",
	"localhost",
	"mail",
	"map",
	"metrics",
	"news",
	"notifications",
	"ops",
	"org",
	"organization",
	"organizations",
	"orgs",
	"plugin",
	"plugins",
	"prod",
	"production",
	"profile",
	"secure",
	"ssh",
	"staging",
	"static",
	"statistics",
	"stats",
	"status",
	"team",
	"wiki",
	"www",

	// TTN
	"applicationserver",
	"as",
	"broker",
	"cli",
	"console",
	"dashboard",
	"ga",
	"gatewayagent",
	"gatewayserver",
	"gs",
	"handler",
	"identityserver",
	"is",
	"joinserver",
	"js",
	"networkserver",
	"noc",
	"ns",
	"router",
	"ttnctl",
	"webui",
)
