name: Merge OS to Enterprise

on: pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  merge-os:
    name: Merge OS to Enterprise
    if: ${{ github.repository == 'TheThingsNetwork/lorawan-stack' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Configure Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to enable full diff
          token: ${{ secrets.BOT_TOKEN }}

      - name: Add TheThingsIndustries remote
        continue-on-error: true
        run: |
          git fetch https://github.com/TheThingsIndustries/lorawan-stack ${{ github.event.pull_request.base.ref }}
          git merge FETCH_HEAD -m "Merge remote/${{ github.event.pull_request.base.ref }} into #${{ github.event.inputs.pull_request_number }}"
          git checkout -b merge/os-to-enterprise

      - name: Create Pull Request using gh
        run: |
          if gh pr list --repo TheThingsIndustries/lorawan-stack --head merge/os-to-enterprise --state open | grep -q "merge/os-to-enterprise"; then
            echo "A pull request already exists, skipping creation."
          else
           gh pr create \
             --repo TheThingsIndustries/lorawan-stack \
             --base v3.34 \
             --head merge/os-to-enterprise \
             --title "Merge changes from TheThingsNetwork/lorawan-stack" \
             --body "This PR automatically syncs changes from the open source repository to the enterprise repository." \
